### PR TITLE
Shutdown command

### PR DESCRIPTION
**Pull request by Seeker1437**
THose would not merge but it has what I did idk if you would use all of it or not, the changes I made to how maint is reported is actually a separate PR I would not implement it until exec approves my PR see aura-project/aura#238

### CODE REVIEW

**Comment by superjeffreyc** [comment]
Alright, thanks. I'll try to resolve the conflicts and merge our code.

**Comment by Seeker1437** [comment]
Sure thing sorry about this!!

**Comment by Seeker1437** [comment]
Whoa I majorly screwed this up

**Comment by Seeker1437** [comment]
Im going to need to redo this PR actually what I'll most likely do is pull from this branch and implement my changes there then it's all up to you what you want me to keep for your or scrap, finally, I will squash all the commits down to one once we have it formulated

**Pull request closed without merging**
